package com.miaoshaproject.dataObject;

import java.util.Date;

public class PromoteDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.promote_name
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private String promoteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.start_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.end_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.item_id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.promote_price
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    private Double promotePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.id
     *
     * @return the value of promote.id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.id
     *
     * @param id the value for promote.id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.promote_name
     *
     * @return the value of promote.promote_name
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public String getPromoteName() {
        return promoteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.promote_name
     *
     * @param promoteName the value for promote.promote_name
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setPromoteName(String promoteName) {
        this.promoteName = promoteName == null ? null : promoteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.start_date
     *
     * @return the value of promote.start_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.start_date
     *
     * @param startDate the value for promote.start_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.end_date
     *
     * @return the value of promote.end_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.end_date
     *
     * @param endDate the value for promote.end_date
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.item_id
     *
     * @return the value of promote.item_id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.item_id
     *
     * @param itemId the value for promote.item_id
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.promote_price
     *
     * @return the value of promote.promote_price
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public Double getPromotePrice() {
        return promotePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.promote_price
     *
     * @param promotePrice the value for promote.promote_price
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    public void setPromotePrice(Double promotePrice) {
        this.promotePrice = promotePrice;
    }
}