package com.miaoshaproject.dao;

import com.miaoshaproject.dataObject.PromoteDO;

public interface PromoteDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    int insert(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    int insertSelective(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    PromoteDO selectByPrimaryKey(Integer id);

    PromoteDO selectByItemId(Integer itemId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    int updateByPrimaryKeySelective(PromoteDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promote
     *
     * @mbg.generated Mon Apr 15 19:21:42 CST 2019
     */
    int updateByPrimaryKey(PromoteDO record);
}